<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="hp" failures="1" tests="7" name="Test" time="110.377" errors="0" timestamp="2022-04-12T19:23:31 IST">
  <testcase classname="com.vitiger.createContact.TC_01_CreateContactTest" name="createContact" time="6.562"/>
  <testcase classname="com.vitiger.createContact.TC_01_CreateContactTest" name="createContactWithMandatoryField" time="10.843">
    <skipped/>
  </testcase> <!-- createContactWithMandatoryField -->
  <testcase classname="com.vitiger.createContact.TC_01_CreateContactTest" name="createContactWithMandatoryField" time="10.99">
    <skipped/>
  </testcase> <!-- createContactWithMandatoryField -->
  <testcase classname="com.vitiger.createContact.TC_01_CreateContactTest" name="createContactWithMandatoryField" time="10.675">
    <skipped/>
  </testcase> <!-- createContactWithMandatoryField -->
  <testcase classname="com.vitiger.createContact.TC_01_CreateContactTest" name="createContactWithMandatoryField" time="11.374">
    <skipped/>
  </testcase> <!-- createContactWithMandatoryField -->
  <testcase classname="com.vitiger.createContact.TC_01_CreateContactTest" name="createContactWithMandatoryField" time="10.982">
    <skipped/>
  </testcase> <!-- createContactWithMandatoryField -->
  <testcase classname="com.vitiger.createContact.TC_01_CreateContactTest" name="createContactWithMandatoryField" time="11.185">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at com.vitiger.createContact.TC_01_CreateContactTest.createContactWithMandatoryField(TC_01_CreateContactTest.java:71)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- createContactWithMandatoryField -->
</testsuite> <!-- Test -->
